/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vmtrans


// define symbols for command types
enum class CType {
    C_NONE, C_ARITHMETIC, C_PUSH, C_POP, C_LABEL, C_GOTO,
    C_IF, C_FUNCTION, C_RETURN, C_CALL
  }
  

class App {
    val greeting: String
        get() {
            return "Hello World!adasda"
        }
}

fun main() {
    println(App().greeting)
}
