# https://gfgfddgleb.medium.com/how-to-test-your-go-code-with-github-actions-f15881d46089

name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build
      run: cd n2t && go build -v ./...

    - name: Test
      run: cd n2t && go test -v ./...
